name: secondfile

on: 
  workflow_dispatch:
     inputs:
      environment:
         description: This is the option value where environment run
         default: 'dev'
         required: true
         type: choice
         options:
            - dev
            - staging
            - prod
           
jobs:
    code:
      runs-on: ubuntu-latest
      steps:
          - name : checkout
            run: echo "github branch is chnage"
    build:
      needs: [code]
      runs-on: ubuntu-latest
      steps:
          - name: build docker container
            run: echo "docker container build"
    test:
        needs: [build]
        runs-on: ubuntu-latest
        steps:
           - name: tset on container
             run: echo "testing the container"
    deploy:
       needs: [build, test]
       runs-on: ubuntu-latest
       steps:
         - name : depolying the app
           run: echo "the app deploy in the container"
      
        
