name: new cicd

on: 
    workflow_dispatch:
     inputs:
         environment:
          description: This is the default flow
          default: 'dev' 
          required: true
          type: choice
          options:
              - dev
              - stage
              - qa
              - prod

                    
jobs:
    code:
        runs-on: ubuntu-latest
        steps:
            - name: this the coding step
              run: echo "Code check is complete"
    test:
        needs: [code]
        runs-on: ubuntu-latest
        steps:
            - name: this the test step
              run: echo "test check is complete"
    build:
        needs: [code,test]
        runs-on: ubuntu-latest
        steps:
            - name: this the build started
              run: echo "build is under process"
    deployed:
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: deployement started
              run: echo "deployemnet is completed"
        
  
