 name: Dependency scan

 on:
   workflow_call:

 jobs:
   dependency-check:
     runs-on: ubuntu-latest
     steps:
       - name: Code checkout
         uses: actions/checkout@v6

       - name: Set up Python 3.12
         uses: actions/setup-python@v6
            with:
              python-version: "3.12"

       - name: pip dependency audit 
         run: pip install pip-audit
        
       - name: Audit Dependency
         run: pip-audit -r requirement.txt 
       
    