name: Deploy to server

on:
    workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: ssh to pro server
              uses: appleboy/ssh-action@v1
                with:
                    host: ${{ secrets.EC2_SSH_HOST }}
                    username: ${{ secrets.EC2_SSH_USERNAME }}
                    password: ${{ secrets.EC2_SSH_PASSWORD }}
                    script: |
                      echo "Starting deployment"\
                      mkdir devops